spellchecker: hunspell
jobs: 4

matrix:
  - name: markdown-docs
    sources:
      - "doc/**/*.md"
      - "README.md"
      - "info.md"
    hunspell:
      d: en_US
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    dictionary:
      wordlists:
        - .pyspelling-wordlist
      output: build/spelling-docs.dic

  - name: translations-en
    sources:
      - "build/translations/en.txt"
    hunspell:
      d: en_US
    pipeline:
      - pyspelling.filters.text
    dictionary:
      wordlists:
        - .pyspelling-wordlist
      output: build/spelling-en.dic

  - name: translations-de
    sources:
      - "build/translations/de.txt"
    hunspell:
      d: de_DE
    pipeline:
      - pyspelling.filters.text
    dictionary:
      wordlists:
        - .pyspelling-wordlist
      output: build/spelling-de.dic

  - name: translations-fr
    sources:
      - "build/translations/fr.txt"
    hunspell:
      d: fr_FR
    pipeline:
      - pyspelling.filters.text
    dictionary:
      wordlists:
        - .pyspelling-wordlist
      output: build/spelling-fr.dic

  - name: translations-it
    sources:
      - "build/translations/it.txt"
    hunspell:
      d: it_IT
    pipeline:
      - pyspelling.filters.text
    dictionary:
      wordlists:
        - .pyspelling-wordlist
      output: build/spelling-it.dic
