spellchecker: hunspell
jobs: 4

matrix:
  - name: markdown-docs
    sources:
      - "doc/**/*.md"
      - "README.md"
      - "info.md"
    hunspell:
      d: en_US,de_DE,fr_FR,pl_PL,it_IT,nl_NL,sv_SE,nb_NO,da_DK,cs_CZ
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    dictionary:
      wordlists:
        - .pyspelling-wordlist
      output: build/spelling.dic
